# Staging Transformation Configuration
# Source and Staging Database Configuration
source_database: mck_src
staging_database: mck_stg
lkup_db: mck_references

# Dependency groups for controlled table execution order
dependency_groups:
  - group: "wave2_tables"
    description: "Wave 2 tables - Shopify transaction data"
    parallel: true
    depends_on: []
    tables:
      - name: gbq_shopify_transaction_histunion
        source_db: mck_src
        staging_table: gbq_shopify_transaction
        has_dedup: true
        partition_columns: id
        mode: inc
